DROP TABLE IF EXISTS APPLICATION ;
CREATE TABLE APPLICATION
(
    SUBTYPE VARCHAR2(24) NOT NULL,
    APPLICATIONDESCRIPTION VARCHAR2(70) NOT NULL,
    SERVICEABLE VARCHAR2(24) NOT NULL,
    TESTABLE VARCHAR2(24) NOT NULL,
    SELLABLE VARCHAR2(24) NOT NULL,
    RESIDENTONVEHICLE VARCHAR2(24) NOT NULL,
    DIGITALLYSIGNED VARCHAR2(24) NOT NULL,
    CONSUMERVIEWABLE VARCHAR2(24) NOT NULL,
    CONSUMERDOWNLOADABLE VARCHAR2(24) NOT NULL,
    DEALERDOWNLOADABLE VARCHAR2(24) NOT NULL,
    OTAVIEWABLE VARCHAR2(24) NOT NULL,
    OTADOWNLOADABLE VARCHAR2(24) NOT NULL,
	PRIMARY KEY (SUBTYPE)
);


DROP TABLE IF EXISTS FUNCTIONALTYPEVALUES ;
CREATE TABLE FUNCTIONALTYPEVALUES
(
    SUBTYPE VARCHAR2(24) NOT NULL,
    FUNCTIONALTYPE VARCHAR2(24) NOT NULL,
    PRIMARY KEY (SUBTYPE)

);


DROP TABLE IF EXISTS COMPATIBLEASSEMBLIES ;
CREATE TABLE COMPATIBLEASSEMBLIES
(
    COMPATIBLE_ID LONG NOT NULL,
    ASSYPN VARCHAR2(24) NOT NULL,
    SUBTYPE VARCHAR2(24) NOT NULL,
    PRIMARY KEY (COMPATIBLE_ID)

);


DROP TABLE IF EXISTS VALUES_TABLE ;
CREATE TABLE VALUES_TABLE
(
    VALUES_ID LONG NOT NULL,
    SUBTYPE VARCHAR2(24) NOT NULL,
    VAL VARCHAR2(24) NOT NULL,
    PRIMARY KEY (VALUES_ID)
);


DROP TABLE IF EXISTS APPLICATIONPARTDETAIL ;
CREATE TABLE APPLICATIONPARTDETAIL
(
    SUBTYPE VARCHAR2(24) NOT NULL,
    FILEPN VARCHAR2(24) NOT NULL,
    FROZENSTATUS VARCHAR2(24) NOT NULL,
    SUCCESSORPARTNUMBER VARCHAR2(24) NOT NULL,
    VERSION VARCHAR2(24) NOT NULL,
    RUNTIMESIZE VARCHAR2(24) NOT NULL,
    PRIMARY KEY (FILEPN, SUBTYPE)
);


DROP TABLE IF EXISTS MGMFILE ;
CREATE TABLE MGMFILE
(
    FILEPN VARCHAR2(24) NOT NULL,
    FILEFORMAT VARCHAR2(24) NOT NULL,
    CHECKSUM VARCHAR2(50) NOT NULL,
    FILEFINGERPRINT VARCHAR2(50) NOT NULL,
    ROMSIZEKB VARCHAR2(24) NOT NULL,
    FILESIZE VARCHAR2(24) NOT NULL,
    FILEDATEMODIFIED VARCHAR2(50) NOT NULL,
    PRIMARY KEY (FILEPN)
);


DROP TABLE IF EXISTS PROTOCOL ;
CREATE TABLE PROTOCOL
(
    FILEPN VARCHAR2(24) NOT NULL,
    NETWORKWIRELESS VARCHAR2(24) NOT NULL,
    NETWORKPROTOCOL VARCHAR2(24) NOT NULL,
    PRIMARY KEY (FILEPN, NETWORKPROTOCOL)
);